from __future__ import annotations

import asyncio
import json
import zipfile
from pathlib import Path

import pytest

import hermes_claude_agent_sdk.parity.runtime_suite as runtime_suite
from hermes_claude_agent_sdk.parity.executors import EXECUTORS
from hermes_claude_agent_sdk.parity.results import ExecutionClassification
from hermes_claude_agent_sdk.parity.efficiency import evaluate_fable_cache_efficiency
from hermes_claude_agent_sdk.parity.runner import ExecutionContext
from hermes_claude_agent_sdk.parity.runtime_suite import (
    RUNTIME_EXECUTION_ID,
    _load_release_receipt,
    _running_package_matches_wheel,
    _turn_content,
    _write_runtime_usage_summary,
    active_runtime_100_turn,
    runtime_execution_ids,
)


def _context(catalog, candidate_fields, **overrides) -> ExecutionContext:
    fields = {
        "capability": catalog.by_id["runtime:active-100-turn"],
        "path": "positive",
        "trial_index": 1,
        "profile_id": candidate_fields["profile_id"],
        "profile_hash": candidate_fields["profile_hash"],
        "plugin_sha": candidate_fields["plugin_sha"],
        "host_sha": candidate_fields["host_sha"],
        "sdk_version": candidate_fields["sdk_version"],
        "runner_version": candidate_fields["runner_version"],
        "inventory_hash": candidate_fields["inventory_hash"],
        "contract_hash": catalog.contract_hash,
        "catalog_hash": catalog.catalog_hash,
        "remaining_turn_budget": 100,
        "repo_root": str(catalog.path.parent.parent),
    }
    fields.update(overrides)
    return ExecutionContext(**fields)


def test_runtime_executor_is_registered_as_one_exact_campaign() -> None:
    assert runtime_execution_ids() == (RUNTIME_EXECUTION_ID,)
    assert EXECUTORS[RUNTIME_EXECUTION_ID] is active_runtime_100_turn
    markers = [f"TURN_{index:03d}_OK" for index in range(1, 101)]
    assert len(set(markers)) == 100
    for index, marker in enumerate(markers, 1):
        assert marker in str(_turn_content(index))


def test_runtime_executor_fails_closed_for_nonpersistent_fixture_profile(
    catalog, candidate_fields, monkeypatch
) -> None:
    monkeypatch.setattr(
        "hermes_claude_agent_sdk.parity.runtime_suite._exact_source_preflight",
        lambda _context, _root: None,
    )
    context = _context(
        catalog,
        candidate_fields,
        profile_isolation_kind="in_process_fixture",
        profile_persistent=False,
    )

    bundle = asyncio.run(active_runtime_100_turn(context))

    assert bundle.turn_count == 0
    assert all(
        outcome.classification is ExecutionClassification.ENVIRONMENT_BLOCKED
        and outcome.reason_code == "runtime_profile_not_persistent_isolated"
        for outcome in bundle.outcomes.values()
    )


def test_release_ready_receipt_binds_issue_artifact_and_exact_heads(
    catalog, candidate_fields, tmp_path: Path
) -> None:
    context = _context(catalog, candidate_fields)
    wheel_hash = "a" * 64
    receipt = {
        "schema_version": 1,
        "issue": 9,
        "status": "release_ready",
        "artifact_immutable": True,
        "plugin_sha": context.plugin_sha,
        "host_sha": context.host_sha,
        "sdk_version": context.sdk_version,
        "wheel_sha256": wheel_hash,
        "contract_hash": context.contract_hash,
        "catalog_hash": context.catalog_hash,
    }
    path = tmp_path / "release-ready.json"
    path.write_text(json.dumps(receipt), encoding="utf-8")

    assert _load_release_receipt(path, context=context, wheel_hash=wheel_hash)
    receipt["artifact_immutable"] = False
    path.write_text(json.dumps(receipt), encoding="utf-8")
    assert not _load_release_receipt(path, context=context, wheel_hash=wheel_hash)


def test_running_package_must_byte_match_the_immutable_wheel(
    tmp_path: Path, monkeypatch
) -> None:
    package_root = tmp_path / "hermes_claude_agent_sdk"
    package_root.mkdir()
    (package_root / "__init__.py").write_bytes(b"package\n")
    (package_root / "runtime.py").write_bytes(b"runtime\n")
    runtime_module = package_root / "parity" / "runtime_suite.py"
    runtime_module.parent.mkdir()
    runtime_module.write_bytes(b"runtime suite\n")
    cache_root = package_root / "__pycache__"
    cache_root.mkdir()
    (cache_root / "runtime.cpython-314.pyc").write_bytes(b"generated cache\n")
    (package_root / "orphan.pyo").write_bytes(b"generated bytecode\n")

    def write_wheel(path: Path, *, include: tuple[str, ...]) -> None:
        with zipfile.ZipFile(path, "w") as archive:
            for relative in include:
                archive.writestr(
                    f"hermes_claude_agent_sdk/{relative}",
                    (package_root / relative).read_bytes(),
                )

    monkeypatch.setattr(runtime_suite, "__file__", str(runtime_module))
    exact_wheel = tmp_path / "exact.whl"
    members = ("__init__.py", "runtime.py", "parity/runtime_suite.py")
    write_wheel(exact_wheel, include=members)
    assert _running_package_matches_wheel(exact_wheel)

    partial_wheel = tmp_path / "partial.whl"
    write_wheel(partial_wheel, include=("__init__.py",))
    assert not _running_package_matches_wheel(partial_wheel)

    extra_source = package_root / "extra.py"
    extra_source.write_bytes(b"extra\n")
    assert not _running_package_matches_wheel(exact_wheel)
    extra_source.unlink()

    extra_data = package_root / "extra.json"
    extra_data.write_bytes(b'{"extra": true}\n')
    assert not _running_package_matches_wheel(exact_wheel)

    tampered_wheel = tmp_path / "tampered.whl"
    with zipfile.ZipFile(tampered_wheel, "w") as archive:
        for relative in (*members, "extra.json"):
            payload = b"tampered" if relative == "__init__.py" else (
                package_root / relative
            ).read_bytes()
            archive.writestr(f"hermes_claude_agent_sdk/{relative}", payload)
    assert not _running_package_matches_wheel(tampered_wheel)


def test_runtime_usage_summary_reports_only_safe_aggregate_and_is_write_once(
    catalog, candidate_fields, tmp_path: Path
) -> None:
    context = _context(catalog, candidate_fields, output_dir=str(tmp_path))
    report = evaluate_fable_cache_efficiency(
        [
            {
                "input_tokens": 20,
                "output_tokens": 5,
                "cache_read_tokens": 80,
                "cache_write_tokens": 0,
            }
            for _ in range(100)
        ]
    )

    summary_hash = _write_runtime_usage_summary(
        tmp_path,
        context=context,
        report=report,
    )
    payload = json.loads(
        (tmp_path / "runtime-usage-summary.json").read_text(encoding="utf-8")
    )

    assert payload["summary_hash"] == summary_hash
    assert payload["sample_count"] == 100
    assert payload["p95_non_cache_share_ppm"] == 200_000
    assert payload["total_input_tokens"] == 2_000
    assert payload["total_cache_read_tokens"] == 8_000
    assert payload["status"] == "PASS"
    assert not any("session" in key or "prompt" in key for key in payload)
    with pytest.raises(OSError, match="already exists"):
        _write_runtime_usage_summary(tmp_path, context=context, report=report)
